// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZomAPIs.Model.Data;

namespace ZomAPIs.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20191219014535_SeedingTest2")]
    partial class SeedingTest2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZomAPIs.Model.MySql.RestaurantInfo", b =>
                {
                    b.Property<int>("ResInfoId")
                        .HasColumnType("int");

                    b.Property<long>("RestaurantHashId")
                        .HasColumnType("bigint");

                    b.Property<string>("RestaurantMongoId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ResInfoId");

                    b.ToTable("RestaurantInfos");

                    b.HasData(
                        new
                        {
                            ResInfoId = 0,
                            RestaurantHashId = 7656439828L,
                            RestaurantMongoId = "5dede56b4a22d82ed1e66095"
                        });
                });

            modelBuilder.Entity("ZomAPIs.Model.MySql.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ScreenName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 0,
                            Email = "junhanliu.leon@gmail.com",
                            FName = "Junhan",
                            LName = "Liu",
                            Password = "Seawave@007",
                            Role = "Manager",
                            ScreenName = "Zayhan"
                        });
                });

            modelBuilder.Entity("ZomAPIs.Model.MySql.UserRestaurant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ResInfoId")
                        .HasColumnName("ResInfoId")
                        .HasColumnType("int");

                    b.Property<int>("BeenThereCount")
                        .HasColumnType("int");

                    b.Property<bool>("Liked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RestaurantInfoResInfoId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ResInfoId");

                    b.HasIndex("RestaurantInfoResInfoId");

                    b.ToTable("UserRestaurants");

                    b.HasData(
                        new
                        {
                            UserId = 0,
                            ResInfoId = 0,
                            BeenThereCount = 1,
                            Liked = true
                        });
                });

            modelBuilder.Entity("ZomAPIs.Model.MySql.UserRestaurant", b =>
                {
                    b.HasOne("ZomAPIs.Model.MySql.RestaurantInfo", "RestaurantInfo")
                        .WithMany("UserRestaurants")
                        .HasForeignKey("RestaurantInfoResInfoId");

                    b.HasOne("ZomAPIs.Model.MySql.User", "User")
                        .WithMany("UserRestaurants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
